fix problem with openmp in mac when install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -194,22 +194,22 @@ if [ $USE_LIBGP == "YES" ]; then
 fi
 
 ## Installing oneDNN
-if [ $USE_ONEDNN == "YES" ]; then
+if [ "$USE_ONEDNN" == "YES" ]; then
  CXX=$USE_CXX ./external/install_oneDNN.sh --jobs=$NJOBS
- if [ ! $? == 0 ]; then
+ if [ ! "$?" == 0 ]; then
   logEcho "[Korali] oneDNN could not be installed/found."
   exitWithError
  fi
 fi
 
 ## Checking for cuDNN
-if [ $USE_CUDNN == "YES" ]; then
- if [ -z $CUDA_ROOT ]; then
+if [ "$USE_CUDNN" == "YES" ]; then
+ if [ -z "$CUDA_ROOT" ]; then
   logEcho "[Korali] The \$CUDA_ROOT environment variable needs to be defined for CUDNN support."
   exitWithError
  fi
  
- if [ -z $CUDNN_ROOT ]; then
+ if [ -z "$CUDNN_ROOT" ]; then
   logEcho "[Korali] The \$CUDNN_ROOT environment variable needs to be defined for CUDNN support."
   exitWithError
  fi
@@ -276,20 +276,20 @@ fi
 
 ######## Determining Library Flags ########
 
-if [ $USE_ONEDNN == "YES" ]; then
+if [ "$USE_ONEDNN" == "YES" ]; then
  DNNLROOT=`readlink external/oneDNNlink`; check
  ONEDNNCFLAGS="-D_KORALI_USE_ONEDNN -I${DNNLROOT}/include"
  ONEDNNLIBS="-Wl,-rpath -Wl,${DNNLROOT}/lib64/ -L${DNNLROOT}/lib64/ -Wl,-rpath -Wl,${DNNLROOT}/lib/ -L${DNNLROOT}/lib -ldnnl"
 fi
 
-if [ $USE_CUDNN == "YES" ]; then
+if [ "$USE_CUDNN" == "YES" ]; then
   CUDNNCFLAGS+=" -D_KORALI_USE_CUDNN -I${CUDA_ROOT}/include -I${CUDNN_ROOT}/include"
   CUDNNLIBS+=" -lcudart -lcudnn -lcudnn_ops_infer -lcudnn_ops_train -lcudnn_cnn_infer -lcudnn_cnn_train -Wl,-rpath -Wl,${CUDA_ROOT}/lib64/ -L${CUDA_ROOT}/lib64/ -Wl,-rpath -Wl,${CUDA_ROOT}/lib -L${CUDA_ROOT}/lib -Wl,-rpath -Wl,${CUDNN_ROOT}/lib64/ -L${CUDNN_ROOT}/lib64/ -Wl,-rpath -Wl,${CUDNN_ROOT}/lib -L${CUDNN_ROOT}/lib"
   logEcho "[Korali] Using CUDA Libraries located at ${CUDA_ROOT}."
   logEcho "[Korali] Using CUDNN Libraries located at ${CUDNN_ROOT}."
 fi
 
-if [ $USE_LIBGP == "YES" ]; then
+if [ "$USE_LIBGP" == "YES" ]; then
  LIBGPROOT=`readlink external/libGPlink`; check
  LIBGPCFLAGS="-D_KORALI_USE_LIBGP -I${LIBGPROOT}/include"
  LIBGPLIBS="-Wl,-rpath -Wl,${LIBGPROOT}/lib64/ -L${LIBGPROOT}/lib64/ -Wl,-rpath -Wl,${LIBGPROOT}/lib -L${LIBGPROOT}/lib -lgp"
@@ -299,12 +299,12 @@ LIBCOROOT=`readlink external/libcolink`; check
 LIBCOCFLAGS="-I${LIBCOROOT}"
 LIBCOLIBS="${LIBCOROOT}/libco.o"
 
-if [ $USE_EIGEN == "YES" ]; then
+if [ "$USE_EIGEN" == "YES" ]; then
  EIGENROOT=`readlink external/eigenlink`; check
  EIGENCFLAGS="-D_KORALI_USE_EIGEN -I${EIGENROOT}/include/eigen3"
 fi
 
-if [ $USE_RTNORM == "YES" ]; then
+if [ "$USE_RTNORM" == "YES" ]; then
  RTNORMROOT=`readlink external/rtnormlink`; check
  RTNORMCFLAGS="-D_KORALI_USE_RTNORM -I${RTNORMROOT}"
  RTNORMLIBS="${RTNORMROOT}/rtnorm.o"
@@ -341,9 +341,36 @@ OMPFLAGS="-fopenmp"
 if [[ "$USE_CXX" == "icpc" || "$USE_CXX" == "icc" ]]; then
  OMPFLAGS="-qopenmp"
 fi
+
 if [[ "$USE_CXX" == "clang++" ]]; then
+ 
+  brew --version > /dev/null 2>&1
+ if [ ! $? == 0 ]; then
+  logEcho "[Korali] Error: brew not found."
+  logEcho "         Solution: install brew from https://brew.sh"
+  exitWithError
+ fi
+ 
+ brew list libomp > /dev/null 2>&1
+ if [ ! $? == 0 ]; then
+  logEcho "[Korali] Error: OpenMP not found."
+  logEcho "         Solution: install it with 'brew install llvm libomp'"
+  logEcho "                   Put in \$/HOME/.bash_profile: export LIBRARY_PATH=\"$LIBRARY_PATH:\`brew --prefix llvm\`\" "
+  exitWithError
+ fi
+
+ if [[ "$LIBRARY_PATH" == *"llvm"* ]]; then
+  logEcho "[Korali] Error: LLVM library path not found in \$LIBRARY_PATH."
+  logEcho "         Solution: Run the commands:"
+  logEcho "           echo \"export LIBRARY_PATH=\"$LIBRARY_PATH:\`brew --prefix llvm\`\" \" >> $HOME/.bash_profile "
+  logEcho "           echo \"source $HOME/.bash_profile "
+  exitWithError
+ fi
+
  OMPFLAGS="-lomp"
+
 fi
+
 
 ######## Checking selected compiler #######
 
